# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "NOS - Development Blog"
email: fra.boffa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The development blog for the N2O powered Hobby Operating System.
baseurl: "/nos" # the subpath of your site, e.g. /blog
url: "https://aomega08.github.com" # the base hostname & protocol for your site
twitter_username:
github_username:  aomega08

# Build settings
markdown: kramdown
